/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Pafeu' at '29.05.19 15:32' with Gradle 2.14.1
 *
 * @author Pafeu, @date 29.05.19 15:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
